#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         4
bspc config window_gap           16
bspc config focused_border_color "#c5c8c6"
bspc config normal_border_color  "#969896"
bspc config presel_feedback_color "#c5c8c6"

bspc config top_padding 4
bspc config bottom_padding 4
bspc config left_padding 4
bspc config right_padding 4

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config focus_by_distance    true
bspc config history_aware_focus  true
bspc config click_to_focus       true

# autostart
xset +fp ~/.fonts
xrdb ~/.Xdefaults &
xcalib ~/.x230.icm &
xsetroot -cursor_name left_ptr &
LowMouse &
feh --bg-fill ~/Pictures/Wallpaper/poly.jpg &
